#
# Run functional tests on browser bot deployed to Azure.
#

pool:
  vmImage: 'vs2017-win2016'

trigger:
- main

pr:
- main

variables:
  TestResourceGroup: 'BrowserBotTest$(Build.BuildId)'
  TestAppServicePlan: 'BrowserBotServicePlan$(Build.BuildId)'
  TestWebApp: 'BrowserBotWebApp$(Build.BuildId)'
  TESTURI: 'https://$(TestWebApp).azurewebsites.net/'
#  AzureSubscription: define this in Azure

steps:

- powershell: |
   # Create DateTimeTag for Resource Group
   $DateTimeTag=Get-Date -Format "yyyy-MM-dd HH:mm:ssK"
   "##vso[task.setvariable variable=DatimeTimeTag]$DateTimeTag";
  displayName: 'Create DateTimeTag for Resource Group'

- task: NodeTool@0
  displayName: use node 12.x
  inputs:
    versionSpec: 12.x

- script: cd libraries/browser-functional-tests/browser-echo-bot && yarn && yarn build
  displayName: yarn install and build browser-echo-bot

- powershell: |
   # Compress Bot Source Code
   cd $(System.DefaultWorkingDirectory)/libraries/browser-functional-tests/browser-echo-bot/dist
   $DirToCompress = "$(System.DefaultWorkingDirectory)/libraries/browser-functional-tests/browser-echo-bot/dist"
   $files = Get-ChildItem -Path $DirToCompress
   $ZipFileResult="$(System.DefaultWorkingDirectory)/libraries/browser-functional-tests/browser-echo-bot/browser-echo-bot.zip"
   Compress-Archive -Path $files -DestinationPath $ZipFileResult
  displayName: 'Compress Bot Source Code'

- task: AzureCLI@1
  displayName: 'Deploy browser bot'
  inputs:
    azureSubscription: '$(AzureSubscription)'
    scriptLocation: inlineScript
    inlineScript: |
     echo "# Create resource group"
     call az group create -l westus -n "$(TestResourceGroup)" --tags buildURI=$(Build.BuildUri) cause=automation date=$(DateTimeTag)
     
     echo "# Create app service plan"
     call az appservice plan create -g "$(TestResourceGroup)" -n "$(TestAppServicePlan)" --number-of-workers 4 --sku S1
     
     echo "# Create web app"
     call az webapp create -g "$(TestResourceGroup)" -p "$(TestAppServicePlan)" -n "$(TestWebApp)"
     
     echo "# Deploy source code"
     call az webapp deployment source config-zip --resource-group "$(TestResourceGroup)" --name "$(TestWebApp)" --src "$(System.DefaultWorkingDirectory)/libraries/browser-functional-tests/browser-echo-bot/browser-echo-bot.zip"

- script: yarn
  displayName: yarn install

- script: yarn browser-functional-test chrome
  displayName: run chrome tests

- script: yarn browser-functional-test firefox
  displayName: run firefox tests

- task: AzureCLI@1
  displayName: 'Delete Resource Group'
  inputs:
    azureSubscription: '$(AzureSubscription)'
    scriptLocation: inlineScript
    inlineScript: 'call az group delete -n $(TestResourceGroup) --yes'

  condition: succeededOrFailed()
